import logging
from dataclasses import dataclass

from src.lib.assembly.data_structure.string.charset import Charset
from src.lib.misc.exception import UnrecognizedStringType




MENU_CHARSET = {
    "values": {
        0x80: {"string" : "A"},
        0x81: {"string" : "B"},
        0x82: {"string" : "C"},
        0x83: {"string" : "D"},
        0x84: {"string" : "E"},
        0x85: {"string" : "F"},
        0x86: {"string" : "G"},
        0x87: {"string" : "H"},
        0x88: {"string" : "I"},
        0x89: {"string" : "J"},
        0x8A: {"string" : "K"},
        0x8B: {"string" : "L"},
        0x8C: {"string" : "M"},
        0x8D: {"string" : "N"},
        0x8E: {"string" : "O"},
        0x8F: {"string" : "P"},
        0x90: {"string" : "Q"},
        0x91: {"string" : "R"},
        0x92: {"string" : "S"},
        0x93: {"string" : "T"},
        0x94: {"string" : "U"},
        0x95: {"string" : "V"},
        0x96: {"string" : "W"},
        0x97: {"string" : "X"},
        0x98: {"string" : "Y"},
        0x99: {"string" : "Z"},
        0x9A: {"string" : "a"},
        0x9B: {"string" : "b"},
        0x9C: {"string" : "c"},
        0x9D: {"string" : "d"},
        0x9E: {"string" : "e"},
        0x9F: {"string" : "f"},
        0xA0: {"string" : "g"},
        0xA1: {"string" : "h"},
        0xA2: {"string" : "i"},
        0xA3: {"string" : "j"},
        0xA4: {"string" : "k"},
        0xA5: {"string" : "l"},
        0xA6: {"string" : "m"},
        0xA7: {"string" : "n"},
        0xA8: {"string" : "o"},
        0xA9: {"string" : "p"},
        0xAA: {"string" : "q"},
        0xAB: {"string" : "r"},
        0xAC: {"string" : "s"},
        0xAD: {"string" : "t"},
        0xAE: {"string" : "u"},
        0xAF: {"string" : "v"},
        0xB0: {"string" : "w"},
        0xB1: {"string" : "x"},
        0xB2: {"string" : "y"},
        0xB3: {"string" : "z"},
        0xB4: {"string" : "0"},
        0xB5: {"string" : "1"},
        0xB6: {"string" : "2"},
        0xB7: {"string" : "3"},
        0xB8: {"string" : "4"},
        0xB9: {"string" : "5"},
        0xBA: {"string" : "6"},
        0xBB: {"string" : "7"},
        0xBC: {"string" : "8"},
        0xBD: {"string" : "9"},
        0xBE: {"string" : "!"},
        0xBF: {"string" : "?"},
        0xC0: {"string" : "/"},
        0xC1: {"string" : ":"},
        0xC2: {"string" : "”"},
        0xC3: {"string" : "'"},
        0xC4: {"string" : "-"},
        0xC5: {"string" : "."},
        0xC6: {"string" : ","},
        0xC7: {"string" : "…"},
        0xC8: {"string" : ";"},
        0xC9: {"string" : "#"},
        0xCA: {"string" : "+"},
        0xCB: {"string" : "("},
        0xCC: {"string" : ")"},
        0xCD: {"string" : "%"},
        0xCE: {"string" : "~"},
        0xCF: {"string" : "<DOTTED PIPE>"},
        0xD2: {"string" : "="},
        0xD3: {"string" : "¨"},
        0xD4: {"string" : "↑"},
        0xD5: {"string" : "→"},
        0xD6: {"string" : "↙"},
        0xD7: {"string" : "×"},
        0xD8: {"string" : "<KNIFE>"},
        0xD9: {"string" : "<SWORD>"},
        0xDA: {"string" : "<SPEAR>"},
        0xDB: {"string" : "<KATANA>"},
        0xDC: {"string" : "<STAFF>"},
        0xDD: {"string" : "<BRUSH>"},
        0xDE: {"string" : "<SHURIKEN>"},
        0xDF: {"string" : "<SPECIAL>"},
        0xE0: {"string" : "<DART>"},
        0xE1: {"string" : "<CLAW>"},
        0xE2: {"string" : "<SHIELD>"},
        0xE3: {"string" : "<HELMET>"},
        0xE4: {"string" : "<ARMOR>"},
        0xE5: {"string" : "<TOOL>"},
        0xE6: {"string" : "<SCROLL>"},
        0xE7: {"string" : "<RELIC>"},
        0xE8: {"string" : "<WHITE>"},
        0xE9: {"string" : "<BLACK>"},
        0xEA: {"string" : "<GREY>"},
        0xF0: {"string" : "<ATB 0>"},
        0xF1: {"string" : "<ATB 1>"},
        0xF2: {"string" : "<ATB 2>"},
        0xF3: {"string" : "<ATB 3>"},
        0xF4: {"string" : "<ATB 4>"},
        0xF5: {"string" : "<ATB 5>"},
        0xF6: {"string" : "<ATB 6>"},
        0xF7: {"string" : "<ATB 7>"},
        0xF8: {"string" : "<ATB 8>"},
        0xF9: {"string" : "<ATB LEFT BORDER>"},
        0xFA: {"string" : "<ATB RIGHT BORDER>"},
        0xFE: {"string" : " "},
        0xFF: {"string" : "_"},
    }
}
DESCRIPTION_CHARSET = {
    "values": {
        0x01: {"string" : "<LINE>"},
        0x80: {"string" : "A"},
        0x81: {"string" : "B"},
        0x82: {"string" : "C"},
        0x83: {"string" : "D"},
        0x84: {"string" : "E"},
        0x85: {"string" : "F"},
        0x86: {"string" : "G"},
        0x87: {"string" : "H"},
        0x88: {"string" : "I"},
        0x89: {"string" : "J"},
        0x8A: {"string" : "K"},
        0x8B: {"string" : "L"},
        0x8C: {"string" : "M"},
        0x8D: {"string" : "N"},
        0x8E: {"string" : "O"},
        0x8F: {"string" : "P"},
        0x90: {"string" : "Q"},
        0x91: {"string" : "R"},
        0x92: {"string" : "S"},
        0x93: {"string" : "T"},
        0x94: {"string" : "U"},
        0x95: {"string" : "V"},
        0x96: {"string" : "W"},
        0x97: {"string" : "X"},
        0x98: {"string" : "Y"},
        0x99: {"string" : "Z"},
        0x9A: {"string" : "a"},
        0x9B: {"string" : "b"},
        0x9C: {"string" : "c"},
        0x9D: {"string" : "d"},
        0x9E: {"string" : "e"},
        0x9F: {"string" : "f"},
        0xA0: {"string" : "g"},
        0xA1: {"string" : "h"},
        0xA2: {"string" : "i"},
        0xA3: {"string" : "j"},
        0xA4: {"string" : "k"},
        0xA5: {"string" : "l"},
        0xA6: {"string" : "m"},
        0xA7: {"string" : "n"},
        0xA8: {"string" : "o"},
        0xA9: {"string" : "p"},
        0xAA: {"string" : "q"},
        0xAB: {"string" : "r"},
        0xAC: {"string" : "s"},
        0xAD: {"string" : "t"},
        0xAE: {"string" : "u"},
        0xAF: {"string" : "v"},
        0xB0: {"string" : "w"},
        0xB1: {"string" : "x"},
        0xB2: {"string" : "y"},
        0xB3: {"string" : "z"},
        0xB4: {"string" : "0"},
        0xB5: {"string" : "1"},
        0xB6: {"string" : "2"},
        0xB7: {"string" : "3"},
        0xB8: {"string" : "4"},
        0xB9: {"string" : "5"},
        0xBA: {"string" : "6"},
        0xBB: {"string" : "7"},
        0xBC: {"string" : "8"},
        0xBD: {"string" : "9"},
        0xBE: {"string" : "!"},
        0xBF: {"string" : "?"},
        0xC0: {"string" : "/"},
        0xC1: {"string" : ":"},
        0xC2: {"string" : "”"},
        0xC3: {"string" : "'"},
        0xC4: {"string" : "-"},
        0xC5: {"string" : "."},
        0xC6: {"string" : ","},
        0xC7: {"string" : "…"},
        0xC8: {"string" : ";"},
        0xC9: {"string" : "#"},
        0xCA: {"string" : "+"},
        0xCB: {"string" : "("},
        0xCC: {"string" : ")"},
        0xCD: {"string" : "%"},
        0xCE: {"string" : "~"},
        0xCF: {"string" : "*"},
        0xD0: {"string" : "@"},
        0xD1: {"string" : "<NOTE>"},
        0xD2: {"string" : "="},
        0xD3: {"string" : "“"},
        0xD6: {"string" : "<HOLY>"},
        0xD7: {"string" : "×"},
        0xD8: {"string" : "<LIGHTNING>"},
        0xD9: {"string" : "<WIND>"},
        0xDA: {"string" : "<EARTH>"},
        0xDB: {"string" : "<ICE>"},
        0xDC: {"string" : "<FIRE>"},
        0xDD: {"string" : "<WATER>"},
        0xDE: {"string" : "<POISON>"},
        0xFE: {"string" : "<0xFE>"},
        0xFF: {"string" : " "},
    }
}
FIELD_DIALOG_CHARSET = {
    "max_length": 2,
    "values": {
        0x01: {"string": "\n"},
        0x02: {"string": "<TERRA>"},
        0x03: {"string": "<LOCKE>"},
        0x04: {"string": "<CYAN>"},
        0x05: {"string": "<SHADOW>"},
        0x06: {"string": "<EDGAR>"},
        0x07: {"string": "<SABIN>"},
        0x08: {"string": "<CELES>"},
        0x09: {"string": "<STRAGO>"},
        0x0A: {"string": "<RELM>"},
        0x0B: {"string": "<SETZER>"},
        0x0C: {"string": "<MOG>"},
        0x0D: {"string": "<GAU>"},
        0x0E: {"string": "<GOGO>"},
        0x0F: {"string": "<UMARO>"},
        0x10: {"string": "<WAIT 60 FRAMES>"},
        0x11: {"string": "<WAIT 15 FRAMES TIMES: _>", "argument": True},
        0x12: {"string": "<WAIT 1 FRAME>"},
        0x13: {"string": "<PAGE>\n", "length": 2},
        0x14: {"string": "<SPACES: _>", "argument": True},
        0x15: {"string": "<CHOICE>"},
        0x16: {"string": "<WAIT FOR KEY 15 FRAMES TIMES: _>", "argument": True},
        0x17: {"string": "<0x17: _>", "argument": True},
        0x18: {"string": "<0x18: _>", "argument": True},
        0x19: {"string": "<GP>"},
        0x1A: {"string": "<ITEM>"},
        0x1B: {"string": "<SKILL>"},
        0x1C: {"string": "<RARE ITEM>"},
        0x1D: {"string": "<0x1D: _>", "argument": True},
        0x1E: {"string": "<0x1E: _>", "argument": True},
        0x1F: {"string": "<0x1F: _>", "argument": True},
        0x20: {"string": "A"},
        0x21: {"string": "B"},
        0x22: {"string": "C"},
        0x23: {"string": "D"},
        0x24: {"string": "E"},
        0x25: {"string": "F"},
        0x26: {"string": "G"},
        0x27: {"string": "H"},
        0x28: {"string": "I"},
        0x29: {"string": "J"},
        0x2A: {"string": "K"},
        0x2B: {"string": "L"},
        0x2C: {"string": "M"},
        0x2D: {"string": "N"},
        0x2E: {"string": "O"},
        0x2F: {"string": "P"},
        0x30: {"string": "Q"},
        0x31: {"string": "R"},
        0x32: {"string": "S"},
        0x33: {"string": "T"},
        0x34: {"string": "U"},
        0x35: {"string": "V"},
        0x36: {"string": "W"},
        0x37: {"string": "X"},
        0x38: {"string": "Y"},
        0x39: {"string": "Z"},
        0x3A: {"string": "a"},
        0x3B: {"string": "b"},
        0x3C: {"string": "c"},
        0x3D: {"string": "d"},
        0x3E: {"string": "e"},
        0x3F: {"string": "f"},
        0x40: {"string": "g"},
        0x41: {"string": "h"},
        0x42: {"string": "i"},
        0x43: {"string": "j"},
        0x44: {"string": "k"},
        0x45: {"string": "l"},
        0x46: {"string": "m"},
        0x47: {"string": "n"},
        0x48: {"string": "o"},
        0x49: {"string": "p"},
        0x4A: {"string": "q"},
        0x4B: {"string": "r"},
        0x4C: {"string": "s"},
        0x4D: {"string": "t"},
        0x4E: {"string": "u"},
        0x4F: {"string": "v"},
        0x50: {"string": "w"},
        0x51: {"string": "x"},
        0x52: {"string": "y"},
        0x53: {"string": "z"},
        0x54: {"string": "0"},
        0x55: {"string": "1"},
        0x56: {"string": "2"},
        0x57: {"string": "3"},
        0x58: {"string": "4"},
        0x59: {"string": "5"},
        0x5A: {"string": "6"},
        0x5B: {"string": "7"},
        0x5C: {"string": "8"},
        0x5D: {"string": "9"},
        0x5E: {"string": "!"},
        0x5F: {"string": "?"},
        0x60: {"string": "/"},
        0x61: {"string": ":"},
        0x62: {"string": "»"},
        0x63: {"string": "'"},
        0x64: {"string": "-"},
        0x65: {"string": "."},
        0x66: {"string": ","},
        0x67: {"string": "…"},
        0x68: {"string": ";"},
        0x69: {"string": "#"},
        0x6A: {"string": "+"},
        0x6B: {"string": "("},
        0x6C: {"string": ")"},
        0x6D: {"string": "%"},
        0x6E: {"string": "~"},
        0x6F: {"string": "*"},
        0x70: {"string": "@"},
        0x71: {"string": "♪"},
        0x72: {"string": "="},
        0x73: {"string": "«"},
        0x74: {"string": "<0x74>"},
        0x75: {"string": "<0x75>"},
        0x76: {"string": "<HOLY>"},
        0x77: {"string": "<DEATH>"},
        0x78: {"string": "<LIGHTNING>"},
        0x79: {"string": "<WIND>"},
        0x7A: {"string": "<EARTH>"},
        0x7B: {"string": "<ICE>"},
        0x7C: {"string": "<FIRE>"},
        0x7D: {"string": "<WATER>"},
        0x7E: {"string": "<POISON>"},
        0x7F: {"string": " "},
        0x80: {"string": "e ", "length": 2},
        0x81: {"string": " t", "length": 2},
        0x82: {"string": ": ", "length": 2},
        0x83: {"string": "th", "length": 2},
        0x84: {"string": "t ", "length": 2},
        0x85: {"string": "he", "length": 2},
        0x86: {"string": "s ", "length": 2},
        0x87: {"string": "er", "length": 2},
        0x88: {"string": " a", "length": 2},
        0x89: {"string": "re", "length": 2},
        0x8A: {"string": "in", "length": 2},
        0x8B: {"string": "ou", "length": 2},
        0x8C: {"string": "d ", "length": 2},
        0x8D: {"string": " w", "length": 2},
        0x8E: {"string": " s", "length": 2},
        0x8F: {"string": "an", "length": 2},
        0x90: {"string": "o ", "length": 2},
        0x91: {"string": " h", "length": 2},
        0x92: {"string": " o", "length": 2},
        0x93: {"string": "r ", "length": 2},
        0x94: {"string": "n ", "length": 2},
        0x95: {"string": "at", "length": 2},
        0x96: {"string": "to", "length": 2},
        0x97: {"string": " i", "length": 2},
        0x98: {"string": ", ", "length": 2},
        0x99: {"string": "ve", "length": 2},
        0x9A: {"string": "ng", "length": 2},
        0x9B: {"string": "ha", "length": 2},
        0x9C: {"string": " m", "length": 2},
        0x9D: {"string": "Th", "length": 2},
        0x9E: {"string": "st", "length": 2},
        0x9F: {"string": "on", "length": 2},
        0xA0: {"string": "yo", "length": 2},
        0xA1: {"string": " b", "length": 2},
        0xA2: {"string": "me", "length": 2},
        0xA3: {"string": "y ", "length": 2},
        0xA4: {"string": "en", "length": 2},
        0xA5: {"string": "it", "length": 2},
        0xA6: {"string": "ar", "length": 2},
        0xA7: {"string": "ll", "length": 2},
        0xA8: {"string": "ea", "length": 2},
        0xA9: {"string": "I ", "length": 2},
        0xAA: {"string": "ed", "length": 2},
        0xAB: {"string": " f", "length": 2},
        0xAC: {"string": " y", "length": 2},
        0xAD: {"string": "hi", "length": 2},
        0xAE: {"string": "is", "length": 2},
        0xAF: {"string": "es", "length": 2},
        0xB0: {"string": "or", "length": 2},
        0xB1: {"string": "l ", "length": 2},
        0xB2: {"string": " c", "length": 2},
        0xB3: {"string": "ne", "length": 2},
        0xB4: {"string": "'s", "length": 2},
        0xB5: {"string": "nd", "length": 2},
        0xB6: {"string": "le", "length": 2},
        0xB7: {"string": "se", "length": 2},
        0xB8: {"string": " I", "length": 2},
        0xB9: {"string": "a ", "length": 2},
        0xBA: {"string": "te", "length": 2},
        0xBB: {"string": " l", "length": 2},
        0xBC: {"string": "pe", "length": 2},
        0xBD: {"string": "as", "length": 2},
        0xBE: {"string": "ur", "length": 2},
        0xBF: {"string": "u ", "length": 2},
        0xC0: {"string": "al", "length": 2},
        0xC1: {"string": " p", "length": 2},
        0xC2: {"string": "g ", "length": 2},
        0xC3: {"string": "om", "length": 2},
        0xC4: {"string": " d", "length": 2},
        0xC5: {"string": "f ", "length": 2},
        0xC6: {"string": " g", "length": 2},
        0xC7: {"string": "ow", "length": 2},
        0xC8: {"string": "rs", "length": 2},
        0xC9: {"string": "be", "length": 2},
        0xCA: {"string": "ro", "length": 2},
        0xCB: {"string": "us", "length": 2},
        0xCC: {"string": "ri", "length": 2},
        0xCD: {"string": "wa", "length": 2},
        0xCE: {"string": "we", "length": 2},
        0xCF: {"string": "Wh", "length": 2},
        0xD0: {"string": "et", "length": 2},
        0xD1: {"string": " r", "length": 2},
        0xD2: {"string": "nt", "length": 2},
        0xD3: {"string": "m ", "length": 2},
        0xD4: {"string": "ma", "length": 2},
        0xD5: {"string": "I'", "length": 2},
        0xD6: {"string": "li", "length": 2},
        0xD7: {"string": "ho", "length": 2},
        0xD8: {"string": "of", "length": 2},
        0xD9: {"string": "Yo", "length": 2},
        0xDA: {"string": "h ", "length": 2},
        0xDB: {"string": " n", "length": 2},
        0xDC: {"string": "ee", "length": 2},
        0xDD: {"string": "de", "length": 2},
        0xDE: {"string": "so", "length": 2},
        0xDF: {"string": "gh", "length": 2},
        0xE0: {"string": "ca", "length": 2},
        0xE1: {"string": "ra", "length": 2},
        0xE2: {"string": "n'", "length": 2},
        0xE3: {"string": "ta", "length": 2},
        0xE4: {"string": "ut", "length": 2},
        0xE5: {"string": "el", "length": 2},
        0xE6: {"string": "! ", "length": 2},
        0xE7: {"string": "fo", "length": 2},
        0xE8: {"string": "ti", "length": 2},
        0xE9: {"string": "We", "length": 2},
        0xEA: {"string": "lo", "length": 2},
        0xEB: {"string": "e!", "length": 2},
        0xEC: {"string": "ld", "length": 2},
        0xED: {"string": "no", "length": 2},
        0xEE: {"string": "ac", "length": 2},
        0xEF: {"string": "ce", "length": 2},
        0xF0: {"string": "k ", "length": 2},
        0xF1: {"string": " u", "length": 2},
        0xF2: {"string": "oo", "length": 2},
        0xF3: {"string": "ke", "length": 2},
        0xF4: {"string": "ay", "length": 2},
        0xF5: {"string": "w ", "length": 2},
        0xF6: {"string": "!!", "length": 2},
        0xF7: {"string": "ag", "length": 2},
        0xF8: {"string": "il", "length": 2},
        0xF9: {"string": "ly", "length": 2},
        0xFA: {"string": "co", "length": 2},
        0xFB: {"string": ". ", "length": 2},
        0xFC: {"string": "ch", "length": 2},
        0xFD: {"string": "go", "length": 2},
        0xFE: {"string": "ge", "length": 2},
        0xFF: {"string": "e…", "length": 2},
    }
}


DUMMY_CHARSET = {
    "max_length": 3,
    "values": {
        0x01: {"string": "A"},
        0x02: {"string": "<0x02>"},
        0x03: {"string": "<0x03: _>", "argument": True},
        0x04: {"string": "ab", "length": 2},
        0x05: {"string": "\n"},
        0x06: {"string": "<PAGE>\n", "length": 2},
        0x07: {"string": "'"},
        0x08: {"string": "'s", "length": 2},
        0x09: {"string": "123", "length": 3},
        0x0A: {"string": "<ARGUMENT: _>", "argument": True}
    }
}


@dataclass
class StringType:
    """
    StringTypes helps determine how to parse a string in a script. The prefix is a word that precedes the string in a
    script line, such as "desc" for menu descriptions for example. The corresponding charset will be used to parse the
    string.
    """

    prefix: str | None
    charset: Charset
    name: str


class StringTypes:
    MENU = StringType(None, Charset(MENU_CHARSET), "menu")
    DESCRIPTION = StringType("desc", Charset(DESCRIPTION_CHARSET), "description")
    DIALOG = StringType("dlg", Charset(FIELD_DIALOG_CHARSET), "dialog")
    DUMMY_STRING_TYPE = StringType("dummy", Charset(DUMMY_CHARSET), "dummy")

    @classmethod
    def get_by_prefix(cls, prefix: str | None = None) -> StringType:
        """
        Determines the StringType by the script line prefix.
        :param prefix: The word that precedes the string in a script line, such as "desc".
        :return: A StringType.
        :raise UnrecognizedStringType: Raised when the string prefix is unrecognized.
        """
        for string_type in cls.__dict__.values():
            if isinstance(string_type, StringType) and string_type.prefix == prefix:
                return string_type
        else:
            message = f"Prefix '{prefix}' is not recognized."
            logging.error(message)
            raise UnrecognizedStringType(message)

    @classmethod
    def get_by_name(cls, name: str) -> StringType:
        """
        Determines the StringType by its name.
        :param name: The name of the StringType.
        :return: A StringType.
        :raise Unrecognized StringType: Raised when the string prefix is unrecognized.
        """
        if name is not None:
            for string_type in cls.__dict__.values():
                if isinstance(string_type, StringType) and string_type.name == name:
                    return string_type
        message = f"StringType '{name}' is not recognized."
        logging.error(message)
        raise UnrecognizedStringType(message)
